import Head from "next/head";
import { ks } from "@/styles/fonts";
import styles from "./Home.module.scss";
import JobCard from "@/components/JobCard";
import Button from "@/components/Button";

export default function Home() {
  return (
    <>
      <Head>
        <title>devjobs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main className={`${ks.className} ${styles.main}`}>
        <JobCard />
        <JobCard />
        <JobCard />
        <JobCard />
        <JobCard />
        <JobCard />
        <JobCard />
        <JobCard />
        <JobCard />
      </main>
    </>
  );
}
